language: r

warnings_are_errors: true

cache: packages

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - docker pull drill/apache-drill:1.14.0
  - docker run -i --name drill-1.14.0 -p 8047:8047 --detach -t drill/apache-drill:1.14.0 /bin/bash
  - docker ps -a

before_script:
  - sleep 5

after_success:
  - Rscript -e 'covr::codecov()'

r:
 - oldrel
 - release

notifications:
  email:
    - bob@rud.is
